var annotated_dup =
[
    [ "cli", null, [
      [ "detail", null, [
        [ "app_friend_t", "structcli_1_1detail_1_1app__friend__t.html", null ],
        [ "classify_object", "structcli_1_1detail_1_1classify__object.html", null ],
        [ "classify_object&lt; T &gt;", "structcli_1_1detail_1_1classify__object_3_01T_01_4.html", null ],
        [ "element_type", "structcli_1_1detail_1_1element__type.html", "structcli_1_1detail_1_1element__type" ],
        [ "element_type&lt; T &gt;", "structcli_1_1detail_1_1element__type_3_01T_01_4.html", "structcli_1_1detail_1_1element__type_3_01T_01_4" ],
        [ "element_value_type", "structcli_1_1detail_1_1element__value__type.html", "structcli_1_1detail_1_1element__value__type" ],
        [ "error_mixin_t", "classcli_1_1detail_1_1error__mixin__t.html", "classcli_1_1detail_1_1error__mixin__t" ],
        [ "expected_count", "structcli_1_1detail_1_1expected__count.html", null ],
        [ "expected_count&lt; T &gt;", "structcli_1_1detail_1_1expected__count_3_01T_01_4.html", null ],
        [ "ipv4_validator_t", "classcli_1_1detail_1_1ipv4__validator__t.html", null ],
        [ "option_names_t", "structcli_1_1detail_1_1option__names__t.html", "structcli_1_1detail_1_1option__names__t" ],
        [ "pair_adaptor", "structcli_1_1detail_1_1pair__adaptor.html", "structcli_1_1detail_1_1pair__adaptor" ],
        [ "pair_adaptor&lt; T &gt;", "structcli_1_1detail_1_1pair__adaptor_3_01T_01_4.html", "structcli_1_1detail_1_1pair__adaptor_3_01T_01_4" ],
        [ "permission_validator_t", "classcli_1_1detail_1_1permission__validator__t.html", "classcli_1_1detail_1_1permission__validator__t" ],
        [ "program_name_t", "structcli_1_1detail_1_1program__name__t.html", "structcli_1_1detail_1_1program__name__t" ],
        [ "scope_guard_t", "structcli_1_1detail_1_1scope__guard__t.html", "structcli_1_1detail_1_1scope__guard__t" ],
        [ "split_result_t", "structcli_1_1detail_1_1split__result__t.html", "structcli_1_1detail_1_1split__result__t" ],
        [ "subtype_count", "structcli_1_1detail_1_1subtype__count.html", null ],
        [ "subtype_count_min", "structcli_1_1detail_1_1subtype__count__min.html", null ],
        [ "type_count", "structcli_1_1detail_1_1type__count.html", null ],
        [ "type_count&lt; T &gt;", "structcli_1_1detail_1_1type__count_3_01T_01_4.html", null ],
        [ "type_count_base", "structcli_1_1detail_1_1type__count__base.html", null ],
        [ "type_count_base&lt; T &gt;", "structcli_1_1detail_1_1type__count__base_3_01T_01_4.html", null ],
        [ "type_count_min", "structcli_1_1detail_1_1type__count__min.html", null ],
        [ "type_count_min&lt; T &gt;", "structcli_1_1detail_1_1type__count__min_3_01T_01_4.html", null ],
        [ "wrapped_type", "structcli_1_1detail_1_1wrapped__type.html", "structcli_1_1detail_1_1wrapped__type" ],
        [ "wrapped_type&lt; T, def_t &gt;", "structcli_1_1detail_1_1wrapped__type_3_01T_00_01def__t_01_4.html", "structcli_1_1detail_1_1wrapped__type_3_01T_00_01def__t_01_4" ]
      ] ],
      [ "app_t", "classcli_1_1app__t.html", "classcli_1_1app__t" ],
      [ "argument_mismatch_t", "classcli_1_1argument__mismatch__t.html", "classcli_1_1argument__mismatch__t" ],
      [ "as_number_with_unit_t", "classcli_1_1as__number__with__unit__t.html", "classcli_1_1as__number__with__unit__t" ],
      [ "as_size_value_t", "classcli_1_1as__size__value__t.html", "classcli_1_1as__size__value__t" ],
      [ "auto_timer_t", "classcli_1_1auto__timer__t.html", "classcli_1_1auto__timer__t" ],
      [ "bad_name_string_t", "classcli_1_1bad__name__string__t.html", "classcli_1_1bad__name__string__t" ],
      [ "bound_t", "classcli_1_1bound__t.html", "classcli_1_1bound__t" ],
      [ "call_for_all_help_t", "classcli_1_1call__for__all__help__t.html", "classcli_1_1call__for__all__help__t" ],
      [ "call_for_help_t", "classcli_1_1call__for__help__t.html", "classcli_1_1call__for__help__t" ],
      [ "call_for_version_t", "classcli_1_1call__for__version__t.html", "classcli_1_1call__for__version__t" ],
      [ "checked_transformer_t", "classcli_1_1checked__transformer__t.html", "classcli_1_1checked__transformer__t" ],
      [ "config_base_t", "classcli_1_1config__base__t.html", "classcli_1_1config__base__t" ],
      [ "config_error_t", "classcli_1_1config__error__t.html", "classcli_1_1config__error__t" ],
      [ "config_ini_t", "classcli_1_1config__ini__t.html", "classcli_1_1config__ini__t" ],
      [ "config_item_t", "structcli_1_1config__item__t.html", "structcli_1_1config__item__t" ],
      [ "config_t", "classcli_1_1config__t.html", "classcli_1_1config__t" ],
      [ "construction_error_t", "classcli_1_1construction__error__t.html", null ],
      [ "conversion_error_t", "classcli_1_1conversion__error__t.html", "classcli_1_1conversion__error__t" ],
      [ "error_t", "classcli_1_1error__t.html", "classcli_1_1error__t" ],
      [ "excludes_error_t", "classcli_1_1excludes__error__t.html", "classcli_1_1excludes__error__t" ],
      [ "extras_error_t", "classcli_1_1extras__error__t.html", "classcli_1_1extras__error__t" ],
      [ "file_error_t", "classcli_1_1file__error__t.html", "classcli_1_1file__error__t" ],
      [ "file_on_default_path_t", "classcli_1_1file__on__default__path__t.html", "classcli_1_1file__on__default__path__t" ],
      [ "file_size_validator_t", "classcli_1_1file__size__validator__t.html", "classcli_1_1file__size__validator__t" ],
      [ "formatter_base_t", "classcli_1_1formatter__base__t.html", "classcli_1_1formatter__base__t" ],
      [ "formatter_lambda_t", "classcli_1_1formatter__lambda__t.html", "classcli_1_1formatter__lambda__t" ],
      [ "formatter_t", "classcli_1_1formatter__t.html", "classcli_1_1formatter__t" ],
      [ "horrible_error_t", "classcli_1_1horrible__error__t.html", "classcli_1_1horrible__error__t" ],
      [ "incorrect_construction_t", "classcli_1_1incorrect__construction__t.html", "classcli_1_1incorrect__construction__t" ],
      [ "invalid_error_t", "classcli_1_1invalid__error__t.html", "classcli_1_1invalid__error__t" ],
      [ "is_member_t", "classcli_1_1is__member__t.html", "classcli_1_1is__member__t" ],
      [ "is_member_type_t", "structcli_1_1is__member__type__t.html", "structcli_1_1is__member__type__t" ],
      [ "is_member_type_t&lt; const char * &gt;", "structcli_1_1is__member__type__t_3_01const_01char_01_5_01_4.html", "structcli_1_1is__member__type__t_3_01const_01char_01_5_01_4" ],
      [ "option_already_added_t", "classcli_1_1option__already__added__t.html", "classcli_1_1option__already__added__t" ],
      [ "option_base_t", "classcli_1_1option__base__t.html", "classcli_1_1option__base__t" ],
      [ "option_defaults_t", "classcli_1_1option__defaults__t.html", "classcli_1_1option__defaults__t" ],
      [ "option_group_t", "classcli_1_1option__group__t.html", "classcli_1_1option__group__t" ],
      [ "option_not_found_t", "classcli_1_1option__not__found__t.html", "classcli_1_1option__not__found__t" ],
      [ "option_t", "classcli_1_1option__t.html", "classcli_1_1option__t" ],
      [ "parse_error_t", "classcli_1_1parse__error__t.html", null ],
      [ "range_t", "classcli_1_1range__t.html", "classcli_1_1range__t" ],
      [ "required_error_t", "classcli_1_1required__error__t.html", "classcli_1_1required__error__t" ],
      [ "requires_error_t", "classcli_1_1requires__error__t.html", "classcli_1_1requires__error__t" ],
      [ "runtime_error_t", "classcli_1_1runtime__error__t.html", "classcli_1_1runtime__error__t" ],
      [ "success_t", "classcli_1_1success__t.html", "classcli_1_1success__t" ],
      [ "timer_t", "classcli_1_1timer__t.html", "classcli_1_1timer__t" ],
      [ "transformer_t", "classcli_1_1transformer__t.html", "classcli_1_1transformer__t" ],
      [ "type_validator_t", "classcli_1_1type__validator__t.html", "classcli_1_1type__validator__t" ],
      [ "validation_error_t", "classcli_1_1validation__error__t.html", "classcli_1_1validation__error__t" ],
      [ "validator_t", "classcli_1_1validator__t.html", "classcli_1_1validator__t" ]
    ] ]
];