file(GLOB_RECURSE srcs CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
add_library(cli11)
target_sources(cli11 PUBLIC FILE_SET CXX_MODULES FILES ${srcs})
set_target_properties(cli11 PROPERTIES EXPORT_NAME "library")
install(
    TARGETS cli11
    EXPORT cli11-targets
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    FILE_SET CXX_MODULES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/cli11)
install(
    PACKAGE_INFO cli11
    EXPORT cli11-targets
    DESTINATION ${CMAKE_INSTALL_LIBDIR}/cps/cli11
    CXX_MODULES_DIRECTORY cxxmodules)
